//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefectiveProduct
    {
        public int DefectiveProductId { get; set; }
        public int ProcessId { get; set; }
        public int LotId { get; set; }
        public int BarcodeId { get; set; }
        public int ErrorCodeId { get; set; }
        public int EmployeeId { get; set; }
        public byte[] ProductImage { get; set; }
        public System.DateTime WorkDate { get; set; }
    
        public virtual Barcode Barcode { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ErrorCode ErrorCode { get; set; }
        public virtual Lot Lot { get; set; }
        public virtual Process Process { get; set; }
    }
}
