//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.DefectiveProducts = new HashSet<DefectiveProduct>();
            this.TotalMonitorings = new HashSet<TotalMonitoring>();
        }
    
        public int EmployeeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public System.DateTime EmploymentDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public int Grade { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefectiveProduct> DefectiveProducts { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TotalMonitoring> TotalMonitorings { get; set; }
    }
}
