//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilitiesHistory
    {
        public int FacilitiesHistoryId { get; set; }
        public System.DateTime WorkDate { get; set; }
        public int FacilitiesId { get; set; }
        public int WorkPlaceId { get; set; }
        public int FHistoryDivisionId { get; set; }
        public string HistoryContent { get; set; }
        public string OCompanyName { get; set; }
        public string OCompanyPhoneNum { get; set; }
        public string OCompanyEmployee { get; set; }
        public string PowerState { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual FHistoryDivision FHistoryDivision { get; set; }
    }
}
