//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirstInspection
    {
        public int FirstInspectionId { get; set; }
        public string OCompanyName { get; set; }
        public int ItemId { get; set; }
        public System.DateTime EnterDate { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public int EnterQuantity { get; set; }
        public Nullable<int> CheckQuantiy { get; set; }
        public Nullable<bool> passQuantity { get; set; }
        public Nullable<int> ErrorQuantity { get; set; }
        public int EmployeeId { get; set; }
        public int WorkPlaceId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Item Item { get; set; }
        public virtual WorkPlace WorkPlace { get; set; }
    }
}
