//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotBarCode
    {
        public int LotId { get; set; }
        public int BarcodeId { get; set; }
        public Nullable<bool> dummy { get; set; }
    
        public virtual Barcode Barcode { get; set; }
        public virtual Lot Lot { get; set; }
    }
}
