//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsInRe
    {
        public int MaterialsInReId { get; set; }
        public int BarcodeId { get; set; }
        public int ProcessId { get; set; }
        public string CurrentState { get; set; }
        public int PassProductQuantity { get; set; }
        public int FailProductQuantity { get; set; }
        public int WorkPlaceId { get; set; }
        public int InputQuantity { get; set; }
    
        public virtual Barcode Barcode { get; set; }
        public virtual Process Process { get; set; }
        public virtual WorkPlace WorkPlace { get; set; }
    }
}
