//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCBVIEntities : DbContext
    {
        public PCBVIEntities()
            : base("name=PCBVIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barcode> Barcodes { get; set; }
        public virtual DbSet<DefectiveProduct> DefectiveProducts { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<ErrorCode> ErrorCodes { get; set; }
        public virtual DbSet<ErrorKind> ErrorKinds { get; set; }
        public virtual DbSet<ErrorType> ErrorTypes { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<FacilitiesHistory> FacilitiesHistories { get; set; }
        public virtual DbSet<FacilitiesPower> FacilitiesPowers { get; set; }
        public virtual DbSet<FHistoryDivision> FHistoryDivisions { get; set; }
        public virtual DbSet<FirstInspection> FirstInspections { get; set; }
        public virtual DbSet<FirstItemDivision> FirstItemDivisions { get; set; }
        public virtual DbSet<InspectionStandard> InspectionStandards { get; set; }
        public virtual DbSet<InspectionStandardType> InspectionStandardTypes { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<LastInspection> LastInspections { get; set; }
        public virtual DbSet<Lot> Lots { get; set; }
        public virtual DbSet<LotBarCode> LotBarCodes { get; set; }
        public virtual DbSet<MaterialHistory> MaterialHistories { get; set; }
        public virtual DbSet<MaterialsInRe> MaterialsInRes { get; set; }
        public virtual DbSet<MaterialsManage> MaterialsManages { get; set; }
        public virtual DbSet<MaterialState> MaterialStates { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<ProcessDefect> ProcessDefects { get; set; }
        public virtual DbSet<ProductionHistory> ProductionHistories { get; set; }
        public virtual DbSet<RotationGroup> RotationGroups { get; set; }
        public virtual DbSet<SecondItemDivision> SecondItemDivisions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TotalMonitoring> TotalMonitorings { get; set; }
        public virtual DbSet<WorkLog> WorkLogs { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<WorkPlace> WorkPlaces { get; set; }
    }
}
