//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessDefect
    {
        public int ProcessDefectId { get; set; }
        public int ErrorCodeId { get; set; }
        public double DefectRate { get; set; }
        public int ProcessId { get; set; }
        public int ItemId { get; set; }
        public System.DateTime WorkDate { get; set; }
    
        public virtual ErrorCode ErrorCode { get; set; }
        public virtual Item Item { get; set; }
        public virtual Process Process { get; set; }
    }
}
