//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionHistory()
        {
            this.FacilitiesPowers = new HashSet<FacilitiesPower>();
        }
    
        public int ProductionHistoryId { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public int ProcessId { get; set; }
        public int ItemId { get; set; }
        public int PassQuantity { get; set; }
        public int ErrorQuantity { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacilitiesPower> FacilitiesPowers { get; set; }
        public virtual Item Item { get; set; }
        public virtual Process Process { get; set; }
    }
}
