//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalMonitoring
    {
        public int TotalMonitoringId { get; set; }
        public int ProcessId { get; set; }
        public int EmployeeId { get; set; }
        public int ItemId { get; set; }
        public int WorkLogId { get; set; }
        public double FacilitiesRate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Item Item { get; set; }
        public virtual Process Process { get; set; }
        public virtual WorkLog WorkLog { get; set; }
    }
}
