//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkLog()
        {
            this.TotalMonitorings = new HashSet<TotalMonitoring>();
        }
    
        public int WorkLogId { get; set; }
        public int RotationGroupId { get; set; }
        public System.DateTime WorkDate { get; set; }
        public System.DateTime SartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> ProductionQuantity { get; set; }
        public Nullable<int> ErrorQuantity { get; set; }
        public int TargetQuantity { get; set; }
        public int ProcessId { get; set; }
        public int FacilitiesId { get; set; }
        public int WorkOrderId { get; set; }
        public int ItemId { get; set; }
        public string WorkerName { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual Item Item { get; set; }
        public virtual Process Process { get; set; }
        public virtual RotationGroup RotationGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TotalMonitoring> TotalMonitorings { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
