//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public int WorkOrderId { get; set; }
        public int ItemId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int RotationGroupId { get; set; }
        public int TargetQuantity { get; set; }
        public int ProcessId { get; set; }
        public int WorkPlaceId { get; set; }
        public string Note { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Process Process { get; set; }
        public virtual RotationGroup RotationGroup { get; set; }
        public virtual WorkPlace WorkPlace { get; set; }
    }
}
